### PR TITLE
Deprecate #progressivelyDecodable

### LINKED ISSUE #272: Should ittp:progressivelyDecodable be deprecated?
Is it actively used? If so, addition to TTML2 should be considered.

### PR DESCRIPTION
**Pull request by palemieux**
Close #272

### CODE REVIEW

**Comment by palemieux** [comment]
> I am not sure if we really need to state the deprecation reason, but if we are going to, then I suggest that we also point out the alternative, which is to segment the caption presentation temporally and deliver consecutive documents each of which has a shorter duration and can be decoded in its entirety, removing any need for progressive decoding.

Isn't this specified somewhere in TTML2? If not, it should be.

**Comment by skynavga** [comment]
TTML{1,2} makes no assumptions about progressive decoding, so it should be
silent.

**Comment by palemieux** [comment]
@skynavga See https://www.w3.org/TR/ttml2/#streaming

**Comment by skynavga** [comment]
ok, but that is informative only; I see no reason to change it since it is
factually correct

**Pull request merged**
