### PR TITLE
Clarify #extent-region constraints

### LINKED ISSUE #469: Clarify that the constraint on `#extent-region` does not require region elements to exist
The constraint in §8.4.2 `#extent-region` that `tts:extent` shall be present on all `region` elements makes no statement about the default region, which of course has no corresponding `region` element. It may be worth clarifying that the constraint does not in and of itself require that `region `elements are present in the document instance, and that the constraint in any case would not apply to the default region where the equivalent extent would be `"100% 100%"` by definition.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #469

### CODE REVIEW

**Comment by palemieux** [comment]
@nigelmegitt Yes, the region constraints could be improved overall. I think https://github.com/w3c/imsc/issues/475 is good opportunity to take a holistic view, and plan to propose an approach that takes https://github.com/w3c/imsc/pull/480#pullrequestreview-258304107 into account.

**Comment by nigelmegitt** [comment]
OK, I've copied my review comment across to #475 so it can be taken into account there.

**Comment by palemieux** [comment]
Superseded by #482. Propose to close.

**Comment by palemieux** [comment]
@nigelmegitt Ok to close this in light of #482?

**Comment by nigelmegitt** [comment]
Closing,

**Pull request closed without merging**
