### PR TITLE
Clarify that tts:backgroundColor does not apply to br or span where tts:ruby is "none"

### LINKED ISSUE #571: span elements are included in NBG(R_i)
The quantity NBG(R<sub>i</sub>) counts the number of `tts:backgroundColor` attributes specified  `span` elements. 

The application of background on a span element is however more akin to the application of a color or font style.

`span` should be excluded from NBG(R<sub>i</sub>) computation, and `tts:backgroundColor` should instead be included in the list of glyph properties at https://www.w3.org/TR/ttml-imsc1.1/#paint-text.

### LINKED ISSUE #574: br elements are included in NBG(R_i)
`br` elements are included in `NBG(R_i)` even though `tts:backgroundColor` does not apply to them and they do not generate any marks.

### PR DESCRIPTION
**Pull request by palemieux**
Closes #571
Closes #574

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/573.html" title="Last updated on Jul 14, 2021, 9:58 PM UTC (eaef1d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/573/e2f3cde...eaef1d3.html" title="Last updated on Jul 14, 2021, 9:58 PM UTC (eaef1d3)">Diff</a>

### CODE REVIEW

**Comment by palemieux** [comment]
I recommend closing this PR without merging based on https://github.com/w3c/imsc/issues/571#issuecomment-884576312

**Review by nigelmegitt — COMMENTED** [review]
It looks like at some point I was mid-way through a review and had made this comment. In the light of the proposal to change, submitting anyway in case it gets reopened.

**Comment by nigelmegitt** [comment]
> I recommend closing this PR without merging based on [#571 (comment)](https://github.com/w3c/imsc/issues/571#issuecomment-884576312)

Perhaps changing it to a Draft Pull Request would be a better reflection of the status? However, I cannot see a button to do that in the GitHub UI right now.

**Comment by palemieux** [comment]
> Perhaps changing it to a Draft Pull Request would be a better reflection of the status? However, I cannot see a button to do that in the GitHub UI right now.

I would just close it.

**Pull request closed without merging**
