### PR TITLE
WIP: IMSC 1.2 CR1

### LINKED ISSUE #529: Reference WHATWG HTML instead of W3C HTML5
Reference to html need to be WHATWG's html instead of html5 at W3C.
please refer also: https://github.com/w3c/transitions/issues/234#issuecomment-599529863

_Originally posted by @himorin in https://github.com/w3c/imsc/pull/525#issuecomment-599671034_

### PR DESCRIPTION
**Pull request by palemieux**
IMSC 1.2 CR release branch

Closes #529 

_DO NOT MERGE_

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/pull/525.html" title="Last updated on Mar 23, 2020, 3:16 PM UTC (3950fae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/imsc/525/4b72015...3950fae.html" title="Last updated on Mar 23, 2020, 3:16 PM UTC (3950fae)">Diff</a>

### CODE REVIEW

**Comment by himorin** [comment]
(removed edit by PR Preview from initial comment, for test. below is the original which was removed)



***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 13, 2020, 2:51 PM UTC)_.

<details>
<summary>More</summary>


PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fimsc%2F2ded3504e84daf131a8bb1eaff455e28fcd4db99%2Fimsc1%2Fspec%2Fttml-ww-profiles.html%3FisPreview%3Dtrue)

```
Navigation timeout of 30000 ms exceeded
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/imsc%23525.)._
</details>

**Comment by himorin** [comment]
Reference to html need to be WHATWG's html instead of html5 at W3C.
please refer also: https://github.com/w3c/transitions/issues/234#issuecomment-599529863

**Comment by himorin** [comment]
I've updated my local copy to branch HEAD after respec processing
https://ttml-w3c.himor.in/CR-ttml-imsc1.2-20200324/
and original copy from this branch is
https://ttml-w3c.himor.in/CR-ttml-imsc1.2-20200324/Overview_orig.html

**Comment by palemieux** [comment]
@himorin What is the revised CR end date?

**Comment by nigelmegitt** [comment]
@palemieux I see May 5.

**Comment by palemieux** [comment]
> I see May 5.

@nigelmegitt Did this change since the transition was moved from March 19 to March 23?

**Comment by nigelmegitt** [comment]
> Did this change since the transition was moved from March 19 to March 23?

@palemieux I don't know, but it's an acceptable earliest date for publication on March 24, I believe.

**Comment by himorin** [comment]
> > I see May 5.
> 
> @nigelmegitt Did this change since the transition was moved from March 19 to March 24?

I believe yes. that date is calculated automatically as 4w later from date of PR publication by default in calculation tool.

**Comment by palemieux** [comment]
Closed per publication at https://www.w3.org/TR/2020/CR-ttml-imsc1.2-20200324/

**Pull request closed without merging**
